import type { Store, Deal } from "./domain";
export function demoData(center: [number, number]) {
  const entries: [
    string,
    Store["category"],
    number,
    number,
    number,
    string,
    string[],
  ][] = [
    [
      "赵一鸣零食 · 街角店",
      "snack",
      0.003,
      0.0018,
      3.9,
      "小袋零食示例价",
      ["量贩零食", "按需买更省"],
    ],
    [
      "好特卖 HotMaxx · 城市店",
      "discount",
      -0.005,
      0.004,
      5.9,
      "饮料示例价",
      ["品牌折扣", "留意保质期"],
    ],
    [
      "社区食堂 · 幸福里",
      "meal",
      0.006,
      -0.0035,
      12,
      "一荤一素示例价",
      ["工作日午饭", "单人友好"],
    ],
    [
      "零食很忙 · 巷口店",
      "snack",
      -0.007,
      -0.003,
      2.5,
      "饼干示例价",
      ["量贩零食", "散称小份"],
    ],
    [
      "名创优品 · 步行街店",
      "daily",
      0.011,
      0.0045,
      10,
      "日用品示例价",
      ["日用百货", "先比单价"],
    ],
    [
      "邻里农贸市场",
      "market",
      -0.012,
      0.007,
      4.5,
      "时令蔬菜示例价",
      ["时令生鲜", "按斤比价"],
    ],
    [
      "嗨特购 · 社区店",
      "discount",
      0.015,
      -0.008,
      6.9,
      "临期食品示例价",
      ["食品折扣", "确认日期"],
    ],
    [
      "沙县小吃 · 老街店",
      "meal",
      -0.004,
      -0.012,
      9,
      "拌面示例价",
      ["平价主食", "日常刚需"],
    ],
    [
      "三福 · 商业街店",
      "daily",
      -0.018,
      -0.008,
      15,
      "小物件示例价",
      ["日用小物", "理性囤货"],
    ],
    [
      "蜜雪冰城 · 广场店",
      "meal",
      0.016,
      0.013,
      4,
      "柠檬水示例价",
      ["平价饮品", "自带杯线索"],
    ],
    [
      "好特卖 HotMaxx · 邻里店",
      "discount",
      -0.022,
      0.015,
      7.9,
      "洗护示例价",
      ["折扣日用", "按需购买"],
    ],
    [
      "十元生活馆",
      "daily",
      0.023,
      -0.012,
      10,
      "生活用品示例价",
      ["平价百货", "小额采购"],
    ],
  ];
  const stores: Store[] = entries.map(
    ([name, category, x, y, price, priceNote, tags], i) => ({
      id: `demo-${center.join(",")}-${i}`,
      name,
      category,
      location: [center[0] + x, center[1] + y],
      price,
      priceNote,
      tags,
      address: `演示街区 · ${["街角路", "邻里路", "生活路"][i % 3]} ${18 + i * 7} 号（虚构地址）`,
      source: "demo",
    }),
  );
  const expiresAt = new Date(Date.now() + 3 * 86400000).toISOString();
  const common = {
    expiresAt,
    source: "demo" as const,
    sourceUrl: "",
    createdAt: new Date().toISOString(),
  };
  const deals: Deal[] = [
    {
      ...common,
      id: "sample-free",
      storeId: stores[2].id,
      title: "双人午餐霸王餐",
      kind: "free",
      price: 0,
      minSpend: 0,
      lottery: true,
      requirements:
        "示例规则：先报名抽签，中签后预约；到店后发布真实体验。不保证中奖。",
    },
    {
      ...common,
      id: "sample-checkin",
      storeId: stores[9].id,
      title: "打卡领取一杯柠檬水",
      kind: "checkin",
      price: 0,
      minSpend: 0,
      lottery: false,
      requirements:
        "示例规则：新用户到店打卡，每人限一杯，不要求额外消费，库存有限。",
    },
    {
      ...common,
      id: "sample-discount",
      storeId: stores[1].id,
      title: "临期零食组合特价",
      kind: "discount",
      price: 9.9,
      minSpend: 0,
      lottery: false,
      requirements:
        "示例规则：指定组合，需到店确认保质期与库存，不叠加其他优惠。",
    },
    {
      ...common,
      id: "sample-required",
      storeId: stores[7].id,
      title: "满 20 元赠送小食",
      kind: "checkin",
      price: 0,
      minSpend: 20,
      lottery: false,
      requirements:
        "示例规则：先消费满 20 元，再领取指定小食；不能单独免费领取。",
    },
  ];
  return { stores, deals };
}
